### PR TITLE
feat: Throw error when class is initialized multiple times

### PR DESCRIPTION
**Pull request by billyvg**
Initializing the plugin class multiple times will cause unwanted behavior (e.g. duplicate listeners). This will cause an increase of user system resources

### CODE REVIEW

**Review by JoshFerge — COMMENTED** [review]
i'm curious how the main sentry js sdk handles this -- what if somehow we're loaded by two different teams or something?

**Comment by billyvg** [comment]
Can we grab your thoughts here @AbhiPrasad @lobsterkatie?

**Comment by lobsterkatie** [comment]
The way it works with the JS SDK is that all of our wrapping is done by integrations, in their respective `setupOnce` methods, and any given integration class [will only install itself once](https://github.com/getsentry/sentry-javascript/blob/d1f0b608682c68733861fe54c0f060da50dadf03/packages/core/src/integration.ts#L91). (Also, in many of the places we wrap things, we mark them as wrapped and [won't wrap them twice](https://github.com/getsentry/sentry-javascript/blob/d1f0b608682c68733861fe54c0f060da50dadf03/packages/browser/src/helpers.ts#L60-L65).)

This is good in terms of not double/triple/etc wrapping things, but bad in terms of supporting multiple sentry instances on the same page, a.k.a. the mulit-hub/micro-frontend problem.

**Comment by billyvg** [comment]
Thanks @lobsterkatie -- I'll hold off on this problem for now while I look into this. I wonder how/if replays could work for microfrontends (e.g. if we could record them all together and not individually).

**Comment by billyvg** [comment]
@lobsterkatie Kind of off-topic here, but in getsentry, we [avoid adding the replay integration to the SDK entirely](https://github.com/getsentry/getsentry/blob/master/static/getsentry/gsApp/components/replayInit.tsx#L8-L12). The reason why is that we did not want to load the Replay SDK for our customers as this is only loaded for Sentry employees. It's behind a feature flag in flagr, so we need the `organization` object, which means we can't load it where we normally would initialize the SDK. How bad is this and is this something the SDK should support.

**Comment by billyvg** [comment]
@JoshFerge let's get this merged and create a new ticket to figure out what we would need to do to support microfrontends.

**Review by JoshFerge — APPROVED** [review]

**Comment by AbhiPrasad** [comment]
The base SDK (and tracing) doesn't really support microfrontends that well, so I wouldn't put too much effort into this. We've described this a bit here in the `Exceptions/Scope Data Quality` section: https://github.com/getsentry/sentry-javascript/discussions/5878

**Pull request merged**
